# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failue: always
env:
  global:
    - CATKIN_PARALLEL_TEST_JOBS=-p1
    - ROS_PARALLEL_TEST_JOBS=-j1
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=cirkit_unit03_simulator.rosinstall
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh 
