#third_robot:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50    

# Wheel & Steer (rocker_bogie_controller should be used without namespace)
steer_drive_controller:
# third_robot_diff_drive_controller:
    type        : "steer_drive_controller/SteerDriveController"
    #type        : "diff_drive_controller/DiffDriveController"
    #left_wheel  : ['base_to_left_front_wheel', 'base_to_left_rear_wheel']
    #right_wheel : ['base_to_right_front_wheel', 'base_to_right_rear_wheel']
    #left_steer  : ['steer_left_front_joint', 'steer_left_back_joint']
    #right_steer : ['steer_right_front_joint', 'steer_right_back_joint']
    left_wheel  : ['base_to_left_rear_wheel']
    right_wheel : ['base_to_right_rear_wheel']
    rear_wheels : ['base_to_right_rear_wheel', 'base_to_left_rear_wheel']
    front_wheels: ['base_to_right_front_wheel', 'base_to_left_front_wheel']
    rear_wheel  : 'base_to_wheel'
    front_steer : 'base_to_steer'
    publish_rate: 100

    pose_covariance_diagonal : [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0
    cmd_vel_timeout: 20
    base_frame_id: base_link

    enable_odom_tf: true
    wheel_separation_w : 0.5
    #wheel_separation_w : 0.26
    #wheel_separation_h : 0.4
    wheel_radius : 0.28

    gazebo:
        virtual_rear_wheels  : ['base_to_right_rear_wheel', 'base_to_left_rear_wheel']
        virtual_front_wheels: ['base_to_right_front_wheel', 'base_to_left_front_wheel']
        virtual_front_steers : ['base_to_right_front_steer', 'base_to_left_front_steer']

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.9  # m/s
        min_velocity           : -0.9 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.7  # m/s^2
        min_acceleration       : -0.4 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.5  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2  #  wheel_right_front_joint_position_controller:
